"""Publication-ready resource-usage statement. Never names individual colleagues."""

from datetime import date
from typing import Any

from mn5_tracker.aggregation import ProjectLifetime
from mn5_tracker.config import Config
from mn5_tracker.reports.summary import Column, render_markdown


STATEMENT_COLUMNS = (
    Column("account", "Allocation"),
    Column("title", "Title"),
    Column("kind", "Type"),
    Column("gpu_hours", "H100 GPU-h", "float0"),
    Column("acc_node_hours", "ACC node-h", "float0"),
    Column("gpp_node_hours", "GPP node-h", "float0"),
)
KIND_LABELS = {"eurohpc": "EuroHPC", "institutional": "BSC internal", "res": "RES"}


def approx(value: float) -> str:
    """36,412 → "36k", 2,498 → "2.5k", 850 → "850"."""
    if value >= 10_000:
        return f"{value / 1000:.0f}k"

    if value >= 1_000:
        return f"{value / 1000:.1f}k"

    return f"{value:.0f}"


def month_label(timestamp: str | None) -> str:
    return date.fromisoformat(timestamp[:10]).strftime("%B %Y") if timestamp else "unknown"


def statement_rows(lifetime: ProjectLifetime, gpus_per_acc_node: int) -> list[dict[str, Any]]:
    rows = []

    for allocation in lifetime.allocations:
        combined = allocation.total_billed_node_hours_by_class
        acc = combined.get("acc", 0.0)
        gpp = combined.get("gpp", 0.0)

        if acc + gpp < 0.5:
            continue

        rows.append(
            {
                "account": allocation.account,
                "title": "" if allocation.title.startswith("unknown") else allocation.title,
                "kind": KIND_LABELS.get(allocation.kind, allocation.kind),
                "gpu_hours": acc * gpus_per_acc_node,
                "acc_node_hours": acc,
                "gpp_node_hours": gpp,
            }
        )

    return sorted(rows, key=lambda row: -row["gpu_hours"])


def build_statement(config: Config, lifetime: ProjectLifetime, today: date) -> str:
    acc_type = config.node_types.get("acc")
    gpus = acc_type.gpus if acc_type else 0
    gpu_model = acc_type.gpu_model if acc_type and acc_type.gpu_model else "GPU"
    lower_bound = lifetime.lower_bound_billed_node_hours_by_class
    acc_node_hours = lower_bound.get("acc", 0.0)
    gpp_node_hours = lower_bound.get("gpp", 0.0)
    others_gpu_hours = lifetime.others_billed_node_hours_by_class.get("acc", 0.0) * gpus
    rows = statement_rows(lifetime, gpus)
    accounts = [str(row["account"]) for row in rows]

    gpp_clause = (
        f" and about {approx(gpp_node_hours)} node-hours on its general-purpose (CPU) partition"
        if gpp_node_hours >= 1
        else ""
    )
    others_clause = (
        f" This includes about {approx(others_gpu_hours)} GPU-hours used by other project members."
        if others_gpu_hours >= 1
        else ""
    )
    period = f"{month_label(lifetime.first_start)} and {month_label(lifetime.last_start)}"
    paragraph = (
        f"Between {period}, "
        f"the {lifetime.title} project used about {approx(acc_node_hours * gpus)} NVIDIA "
        f"{gpu_model} GPU-hours ({approx(acc_node_hours)} node-hours) on the accelerated partition "
        f"of MareNostrum 5 at the Barcelona Supercomputing Center (BSC){gpp_clause}, across "
        f"{len(accounts)} allocations ({', '.join(accounts)}).{others_clause}"
        f"{energy_sentence(config, lifetime)}"
    )

    table_rows = [
        *rows,
        {
            "account": "**Total**",
            "title": "",
            "kind": "",
            "gpu_hours": acc_node_hours * gpus,
            "acc_node_hours": acc_node_hours,
            "gpp_node_hours": gpp_node_hours,
        },
    ]
    sections = [
        f"**Computing resources.** {paragraph}",
        render_markdown(STATEMENT_COLUMNS, table_rows),
        f"_{coverage_note(lifetime)} Generated by mn5track on {today.isoformat()}._",
    ]

    if not config.energy.verified:
        sections.insert(
            0,
            "> **Draft: do not publish the energy and carbon figures.** The energy parameters in "
            "`config/project.yaml` (PUE, GPU power, grid intensity) are not verified yet.",
        )

    acknowledgement = eurohpc_acknowledgement(config, accounts)

    if acknowledgement:
        sections.append(acknowledgement)

    return "\n\n".join(sections) + "\n"


def energy_sentence(config: Config, lifetime: ProjectLifetime) -> str:
    energy = lifetime.energy

    if energy.billed_node_hours < 1:
        return ""

    facility = energy.facility_kwh
    co2e = energy.co2e_kg
    measured = energy.measured_share or 0.0

    return (
        f" We estimate that this corresponds to about {approx_energy(facility['central'])} of "
        f"electricity (range {approx_energy(facility['low'])}–{approx_energy(facility['high'])}, "
        f"including data-centre overhead at a PUE of {config.energy.pue:g}) and about "
        f"{approx_mass(co2e['central'])} CO₂e (range {approx_mass(co2e['low'])}–"
        f"{approx_mass(co2e['high'])}; location-based, Spanish grid). "
        f"Energy was measured by the system for {measured:.0%} of the billed node-hours and "
        "modelled from hardware power for the rest."
    )


def approx_energy(kwh: float) -> str:
    return f"{kwh / 1000:.1f} MWh" if kwh >= 1000 else f"{kwh:.0f} kWh"


def approx_mass(kg: float) -> str:
    return f"{kg / 1000:.1f} t" if kg >= 1000 else f"{kg:.0f} kg"


def coverage_note(lifetime: ProjectLifetime) -> str:
    """How complete the figure is, without naming anyone."""
    detailed = lifetime.members_with_detail
    fallback = lifetime.members_from_bsc_acct_only
    members = "member" if detailed == 1 else "members"
    fallback_clause = (
        f", plus BSC accounting totals for up to {fallback} other members on dedicated allocations"
        if fallback
        else ""
    )

    return (
        f"Billed usage, lower bound: Slurm accounting of {detailed} project {members}"
        f"{fallback_clause}. Shared institutional allocations count only jobs attributed to the "
        "project by members with Slurm data."
    )


def eurohpc_acknowledgement(config: Config, accounts: list[str]) -> str | None:
    eurohpc_accounts = [
        account
        for account in accounts
        if (allocation := config.allocations.get(account)) and allocation.kind == "eurohpc"
    ]

    if not eurohpc_accounts:
        return None

    return (
        "**Acknowledgement (draft; check the wording your grant agreement requires).** We "
        "acknowledge the EuroHPC Joint Undertaking for awarding this project access to the EuroHPC "
        "supercomputer MareNostrum 5, hosted by BSC in Spain, through allocations "
        f"{', '.join(eurohpc_accounts)}."
    )
